seeder para testeo

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -149,6 +149,20 @@ services:
         echo 'Unido a la red ${ZT_NETWORK_ID}, esperando...' &&
         tail -f /dev/null
       "
+  
+  seeder:
+    image: postgres:16
+    depends_on:
+      postgres:
+        condition: service_healthy
+    volumes:
+      - ./databases/postgres/tests_seed.sql:/seed/tests_seed.sql:ro
+    environment:
+      PGPASSWORD: ${POSTGRES_PASSWORD}
+    entrypoint: ["/bin/sh","-c"]
+    command: >
+      "psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -v ON_ERROR_STOP=1 -f /seed/tests_seed.sql &&
+      echo '✅ Datos de prueba cargados' || (echo '❌ Error en seed' && exit 1)"
 
 volumes:
   influxdb2:
